### ISSUE TITLE
The styling of cards is all absurd can someone help with CSS Bootstrap 

### ISSUE THREAD

**Issue by arjunsoota** [arjunsoota/rejected.in#2]
![Screenshot (26)](https://user-images.githubusercontent.com/22565279/66278048-4414ee80-e8c3-11e9-9504-7b1ff9965de9.png)

need to correct this weird behavior of CSS

**Comment by maskott** [comment]
Hi @arjunsoota 👋 . I'm decent with Bootstrap and I like the idea of your project. I'd like to give this a try. Do you have more specifics of what CSS issue you are looking to correct?

**Comment by arjunsoota** [comment]
Hi @maskott @shawnmcgraw I want to achieve something like this !  you may want to visit https://www.rejected.us for a better understanding. Anyways thanks for coming out and helping. I really appreciate that !
![image](https://user-images.githubusercontent.com/22565279/66305054-288a0200-e91c-11e9-8ddd-d4adad40aa8c.png)

**Comment by maskott** [comment]
I think I've got it: https://github.com/arjunsoota/rejected.in/pull/4

Hope this helps!

**Comment by arjunsoota** [comment]
Thanks to @maskott
